Merwin Abba B. Llorin

2ECE-A

### A. Positional and Label Based Slicing

In [6]:
import pandas as pd

#Load the csv file
cars = pd.read_csv('cars.csv')

In [19]:
# Display the shape of the DataFrame
print("Shape of cars:", cars.shape)

# A. Display all column names
print("Column names:")
print(cars.columns.tolist())

# B. Get rows 6 to 10 
cars_6_to_10 = cars.iloc[5:10].copy()

cars_6_to_10

# C. Display selected columns from rows 6 to 10
cars_6_to_10[['Model', 'mpg', 'cyl', 'hp', 'gear']]

Shape of cars: (32, 12)
Column names:
['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

### B. Model Lookup

In [29]:
# B(a) Toyota Corolla
toyota = cars[cars['Model'].str.strip() == 'Toyota Corolla'].copy()

display(toyota)

# B(b) Pontiac Firebird
pontiac = cars.loc[cars['Model'].str.strip() == 'Pontiac Firebird', ['Model', 'mpg', 'hp', 'wt']].copy()

display(pontiac)

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

### C. Multi Model Subsetting

In [32]:
# Create selected_cars DataFrame
selected_cars = cars[cars['Model'].isin(['Datsun 710', 'Lotus Europa', 'Ferrari Dino'])][['Model', 'mpg', 'cyl', 'hp', 'gear']]

# Display DataFrame and shape 
print("Selected Cars:")
print(selected_cars)
print("\nShape of selected_cars:", selected_cars.shape)

Selected Cars:
           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

Shape of selected_cars: (3, 5)